server:
  port: 8080

spring:
  application:
    name: "AuthService"
  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authdb
    username: auth
    password: auth
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
    initialization:
      enabled: false # ponlo en true si quieres que Spring ejecute schema.sql automáticamente

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,loggers"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    pe.com.powerup.auth: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.r2dbc.connection: DEBUG

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
